### ISSUE TITLE
Test Implementation for `Project` Module

### ISSUE THREAD

**Issue by HarshPatel5940** [HarshPatel5940/EzMs-Backend#10]

**Comment by Hrx4** [comment]
Hey @HarshPatel5940  can you please explain the issue? i want to work on it.

**Comment by HarshPatel5940** [comment]
> Hey @HarshPatel5940  can you please explain the issue? i want to work on it.


Hello @Hrx4, sure you can proceed to work on it.

Make sure you have read this comment. 

https://github.com/HarshPatel5940/EzMs-Backend/issues/3#issuecomment-1762925337

**Comment by HarshPatel5940** [comment]
@Hrx4 Feel free to explain your idea here and then start work on it.

**Comment by HarshPatel5940** [comment]
> Hey @HarshPatel5940 can you please explain the issue? i want to work on it.

@Hrx4 You have write tests for the endpoints which are already been created. So to write test you can use [this](https://docs.nestjs.com/recipes/nest-commander) orelse if you have some better alternative. feel free to explain here and then work it.

**Comment by Hrx4** [comment]
Ok , I am starting work on this issue

**Comment by HarshPatel5940** [comment]
Good to hear!

**Comment by Hrx4** [comment]
How can i get the env file?

**Comment by HarshPatel5940** [comment]
> How can i get the env file?
> 

@Hrx4 You can refer to `.env.example`. If you want I can update the Readme file to include some of the steps on how to setup and start.

Let me know if that's necessary?

**Comment by HarshPatel5940** [comment]
@Hrx4 What's the progress update?

**Comment by HarshPatel5940** [comment]
@Hrx4  Please give me an update, or i will have to unassign this issue.
