### ISSUE TITLE
Improve Github Action Workflow

### ISSUE THREAD

**Issue by HarshPatel5940** [HarshPatel5940/EzMs-Backend#12]
Come with idea's on how you can improve the current GitHub workflow. We should be easily able to see what fails and what passes.

> hint: _You can split up into multiple jobs/workflows_

**Comment by Prasanjit-4** [comment]
Assign this issue to me.

**Comment by HarshPatel5940** [comment]
Sure, Next time try to be friendly.

**Comment by HarshPatel5940** [comment]
Feel free to explain your idea here and then start work on it.

**Comment by Prasanjit-4** [comment]
Yeah sorry for the blunt request.

**Comment by HarshPatel5940** [comment]
@Prasanjit-4 what's the update on this?

**Comment by HarshPatel5940** [comment]
@Prasanjit-4 Please give an update.

**Comment by Prasanjit-4** [comment]
Reading up on the topic. Will share ideas soon..
